#General
resource-path: ["resources"] # the resource path

#Filters
filters:
 - pandoc-gls
 - pandoc-ac
 - pandoc-plantuml

#Biblography
citeproc: true
bibliography: [bibliography.bib] # the bibliography files
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl # the citation style

#Generation
table-of-contents: true #should make toc
number-sections: true # should number sections

#Includes
metadata-files:
 - pandoc/preamble.yml
# - pandoc/frontmatter.yml # Include for a simple title page
include-before-body: [LaTeX/titlepage.tex] # Include for an advanced title page
include-after-body: []
include-in-header: []
