#General
resource-path: ["resources"] # the resource path
filters:
  - filters/diagram-generator.lua
  - filters/pandoc-gls.lua
#   - pandoc-ac

#Biblography
citeproc: true
bibliography: [bibliography.bib] # the bibliography files
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl # the citation style (change *.csl to target another style)

#Generation
table-of-contents: true
number-sections: true

#Includes
metadata-files:
  - config/preamble.yml
# - config/frontmatter.yml # Include for a simple title page
include-in-header: []
include-before-body: [LaTeX/titlepage.tex] # Include for an advanced title page
include-after-body: []
