name: Pandoc CI

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
          echo "FILELIST=$(printf '"%s" ' docs/*.md)" >> $GITHUB_ENV
      - uses: docker://thomasweise/docker-pandoc:latest
        with:
          entrypoint: pandoc
          args: -d pandoc/config.yml --lua-filter pandoc-gls.lua --output=output/result.pdf ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output