name: Pandoc CI

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          echo "::set-env name=FILELIST::$(printf '"%s" ' content/*.md)"
      - uses: docker://pandoc/latex:latest
        with:
          args: -d pandoc_config/defaults.yml --output=output/result.pdf ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output